App/Admin/Controllers/FoodController.cs
using Clients.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SharedObjects.Commons;
using SharedObjects.ValueObjects;
using SharedObjects.ViewModels;

namespace Admin.Controllers
{
    [Authorize]
    public class FoodController : Controller
    {
        private readonly IFoodClient _foodClient;
        private readonly ISubCategoryClient _subCategoryClient;

        public FoodController(IFoodClient foodClient, ISubCategoryClient subCategoryClient)
        {
            _foodClient = foodClient;
            _subCategoryClient = subCategoryClient;
        }
        public async Task<IActionResult> Index()
        {
            var foods = await _foodClient.GetAll();
            return View(foods);
        }
        [AllowAnonymous]
        public async Task<IActionResult> GetPagination_Pta([FromBody]PageViewModel model)
        {
            var result = await _foodClient.GetPagination(model);
            return PartialView(result);
        }
        [AllowAnonymous]
        public async Task<JsonResult> CountPagination()
        {
            int count = await _foodClient.CountPagination();
            return Json(new { result = count });
        }
        public async Task<IActionResult> Detail(string foodId)
        {
            VFood food = await _foodClient.GetById(foodId);
            return View(food);
        }
        public async Task<JsonResult> GetById(string foodId)
        {
            var food = await _foodClient.GetById(foodId);
            return Json(new { result = food });
        }
        public async Task<IActionResult> Add(string foodId)
        {
            if (string.IsNullOrEmpty(foodId))
            {
                ViewBag.FoodId = "";
            }
            ViewBag.FoodId = foodId;
            var subcategories = await _subCategoryClient.GetAll();
            return View(subcategories);
        }
        [HttpPost]
        public async Task<JsonResult> Save([FromBody] FoodViewModel model)
        {
            string token = User.GetSpecificClaim("token");
            int result;
            if (string.IsNullOrEmpty(model.FoodId))
            {
                result = await _foodClient.Add(model, token);
                if(result == 200)
                {
                    return Json(new { statusCode = 1 });
                }
                return Json(new { statusCode = result });
            }
            result = await _foodClient.Update(model, token);
            if (result == 200)
            {
                return Json(new { statusCode = 2 });
            }
            return Json(new { statusCode = result });
        }
        public async Task<IActionResult> Delete(string foodId)
        {
            string token = User.GetSpecificClaim("token");
            var result = await _foodClient.Delete(foodId, token);
            return Json(new { statusCode = result });
        }
    }
}

App/Admin/Views/Food/Add.cshtml
@using SharedObjects.ValueObjects
@model List<VSubCategory>
@section Title{
<title>Thêm mới, cập nhật món ăn</title>
}
@section Breadcrumb{
<li class="breadcrumb-item active" aria-current="page">Thêm mới, cập nhật món ăn</li>
}
@section SlimPageTitle{
    Thêm, cập nhật món ăn
}
@section Script{
    <script src="~/js/food.js"></script>
}
<div class="section-wrapper mg-t-20">
    <div class="row">
        <div class="col-md-12">
            <form id="frm-food">
                <p name="FoodId" id="hid-id" hidden >@ViewBag.FoodId</p>
                <div class="form-group">
                    <label>Tên</label>
                    <input id="txt-name" name="Name" class="form-control" />
                </div>
                <div class="form-group">
                    <label>Giá (VNĐ)</label>
                    <input name="Price" id="txt-price" class="form-control" />
                </div>
                <div class="form-group">
                    <label>Ảnh</label>
                    <input name="Image" id="img" class="form-control" />
                </div>
                <div class="form-group">
                    <label>Mô tả ngắn</label>
                    <input name="Description" id="txt-desc" class="form-control" />
                </div>
                <div class="form-group">
                    <label>Nội dung</label>
                    <textarea rows="3" name="Content" id="txt-content" class="form-control"></textarea>
                </div>
                <div class="form-group">
                    <label>Trạng thái</label>
                    <select name="Status" id="status" class="form-control">
                        <option value="0" >InActice</option>
                        <option value="1" selected>Active</option>
                    </select>
                </div>
                <input name="DateCreated" hidden />
                <div class="form-group">
                    <label name="SubCategoryId" class="control-label">Thuộc loại</label>
                    <select id="sub-name" class="form-control">
                        @foreach (var item in Model)
                        {
                            <option value="@item.SubCategoryId">@item.SubCategoryName</option>
                        }
                    </select>
                </div>
                <div class="form-group">
                    <a href="/food/index" class="btn btn-success btn-oblong save">Lưu bài viết</a>
                </div>
            </form>
        </div>
    </div>
</div>

App/Admin/Views/Food/Detail.cshtml
@using SharedObjects.ValueObjects
@model VFood

@{
    ViewData["Title"] = "Chi tiết món ăn";
}
@section Title{
<title>Tất cả món ăn</title>
}
@section Breadcrumb{
<li class="breadcrumb-item"><a asp-controller="Food" asp-action="Index">Tất cả món ăn</a></li>
<li class="breadcrumb-item active" aria-current="page">@Model.Name</li>
}
@section SlimPageTitle{
    Chi tiết món ăn
}
<div class="section-wrapper mg-t-20">
    <label class="section-title">@Model.SubCategoryName</label>
    <div class="row">
        <div class="col-md-6">
            <div class="card bd-0">
                <div class="card-body">
                    <h5 class="card-title tx-medium mg-b-10">@Model.Name</h5>
                    <p class="card-subtitle tx-normal mg-b-15">@Model.Description</p>
                    <p class="card-text">@Model.Content</p>
                    <p class="mg-b-15 text-danger font-weight-bold">@Model.Price.ToString("N0") VNĐ</p>
                    <div class="mg-b-15">
                        <img src="@Model.Image" width=400 class="rounded" />
                    </div>
                    @if ((int)Model.Status == 0)
                    {
                        <p class="card-text ">Trạng thái: Hết hàng</p>
                    }else{
                        <p class="card-text ">Trạng thái: Còn hàng</p>
                    }
                    <p class="card-text ">@Model.DateCreated</p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
        </div>
    </div>
    <a href="@Url.Action("update", "food", new {foodId = @Model.FoodId})" class="btn btn-oblong btn-success mg-b-10">Cập nhật</a>
</div>

App/Admin/Views/Food/GetPagination_Pta.cshtml
@using SharedObjects.ValueObjects
@model List<VFood>

@foreach (var item in Model)
{
    {
        <tr>
            <td><a href="@Url.Action("detail", "food", new {foodId = item.FoodId})">@item.Name</a></td>
            <td>@item.Price.ToString("N0") VNĐ</td>
            <td><img width="100" src="@item.Image" /></td>
            <td>@item.Status</td>
            <td>@item.SubCategoryName</td>
            <td>
                <a id="btn-update" href="@Url.Action("add", "food", new {foodId = @item.FoodId})"><i class="fa fa-edit text-success"></i></a>
                <a class="delete" data-id="@item.FoodId" href=""><i class="fa fa-trash text-danger"></i></a>
            </td>
        </tr>
    }
}

App/Admin/Views/Food/Index.cshtml
@using SharedObjects.ValueObjects
@model List<VFood>

@{
    ViewData["Title"] = "Món ăn";
}
@section Title{
<title>Tất cả món ăn</title>
}
@section Breadcrumb{
<li class="breadcrumb-item active" aria-current="page">Món ăn</li>
}
@section SlimPageTitle{
    Món ăn
}
@section Script{
<script src="~/js/foodpagination.js"></script>
<script src="~/js/food.js"></script>
}
<div class="section-wrapper mg-t-20">
    <label class="section-title">Tất cả món ăn</label>
    <p class="mg-b-20 mg-sm-b-40"></p>
    <a href="@Url.Action("add", "food", new {foodId = ""})" class="btn btn-oblong btn-success mg-b-10 add">Thêm mới</a>

    <div class="table-responsive">
        <table class="table table-bordered mg-b-0 text-center">
            <thead>
                <tr>
                    <th>Tên</th>
                    <th>Giá</th>
                    <th>Ảnh đại diện</th>
                    <th>Trạng thái</th>
                    <th>Thuộc loại</th>
                    <th>#</th>
                </tr>
            </thead>
            <tbody id="table-content">

                @*GetPagination_Pta*@

            </tbody>
        </table>
        <div class="pagination mt-3" id="pagination">
        </div>
    </div><!-- table-responsive -->
</div>